title: I Putu Sukma book
logo: /assets/img/ipsh_logo.png
email: iputusukma@pm.me
description: ---------
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: Financial Econometrics
    icon: <i class="fa-solid fa-subscript"></i>
    link: https://iputusukma-book.github.io/finecon
  - name: Theory of Finance
    icon: <i class="fa-solid fa-book-bookmark"></i>
    link: https://iputusukma-book.github.io/fintheory
  - name: Corporate Finance
    icon: <i class="fa-solid fa-chart-pie"></i>
    link: https://iputusukma-book.github.io/corpfin
  - name: FInancial Reporting
    icon: <i class="fa-solid fa-file-export"></i>
    link: https://iputusukma-book.github.io/fintheory
  - name: Publication
    icon: <i class="fa-solid fa-graduation-cap"></i>
    link: https://iputusukma-book.github.io/publication
  - name: Project
    icon: <i class="fa-solid fa-diagram-project"></i>
    link: https://iputusukma-book.github.io/project
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://linkedin.com/in/iputusukma
  - name: Resume
    icon: <i class="fa-solid fa-address-card"></i>
    link: https://git-iputusukma.github.io


# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
